#define DRAW_RECTANGLE 0
#define DRAW_CIRCLE 1
#define DRAW_ECLIPSE 2
#define DRAW_LINE 3
#define DRAW_BRUSH 4
#define ERASE 5
#define OPEN 6
#define SAVE 7
#define PLUS 8
#define MINUS 9
#define CLEAR 10
#define COLOR 11
#define PALETTE 12
#define HUE_IDX 13
#define DRAW_RECTANGLE 14
